// featured-books.js — 「買える本（新刊が流通する現代の人気書籍）」優先表示リスト
// 目的: 古典は無料代替があり買われにくい。現代の人気作を結果上位に寄せて購入確率を上げる。
// 仕様: 各言語、"タイトル|著者" の完全一致で判定。該当本がその年齢にあれば結果の上位に寄せる。
// 注意: 文字列は books-data-XX.js の実データと完全一致させること（再生成で表記が変わったら要更新）。
// 編集: 載せたい本を追記/削除するだけ。年齢が分散するほど多くの訪問者に効く。
// 選定: 著者の生年1930年以降・出版1980年以降・年齢が広く分散するよう自動抽出。
//       プロパガンダ/自己啓発/政治的に分断的な書籍・著者名が不明(QID)の本は除外済み。
window.FEATURED = {
  en: [
    "Eragon|Christopher Paolini",
    "Eldest|Christopher Paolini",
    "Divergent|Veronica Roth",
    "Welcome to the N.H.K.|Tatsuhiko Takimoto",
    "Brisingr|Christopher Paolini",
    "American Psycho|Bret Easton Ellis",
    "Inheritance|Christopher Paolini",
    "The Perks of Being a Wallflower|Stephen Chbosky",
    "Life, the Universe and Everything|Douglas Adams",
    "Paper Towns|John Green",
    "Miss Peregrine's Home of Peculiar Children|Ransom Riggs",
    "New Moon|Stephenie Meyer",
    "Eclipse|Stephenie Meyer",
    "The Fault in Our Stars|John Green",
    "Fantastic Beasts and Where to Find Them|J. K. Rowling",
    "The Short Second Life of Bree Tanner|Stephenie Meyer",
    "The Forty Rules of Love|Elif Şafak",
    "Homo Deus: A Brief History of Tomorrow|Yuval Noah Harari",
    "The Help|Kathryn Stockett",
    "The Lightning Thief|Rick Riordan",
    "Capital in the Twenty-First Century|Thomas Piketty",
    "The Girl on the Train|Paula Hawkins",
    "The Battle of the Labyrinth|Rick Riordan",
    "Why Nations Fail: The Origins of Power, Prosperity, and Poverty|Daron Acemoğlu",
    "The Hunger Games|Suzanne Collins",
    "Midnight Sun|Stephenie Meyer",
    "The Cuckoo's Calling|J. K. Rowling",
    "Project Hail Mary|Andy Weir",
    "Snow|Orhan Pamuk",
    "Never Let Me Go|Kazuo Ishiguro",
    "Darkly Dreaming Dexter|Jeff Lindsay",
    "Origin|Dan Brown",
    "Dreamcatcher|Stephen King",
    "After Dark|Haruki Murakami",
    "The Museum of Innocence|Orhan Pamuk",
    "A Feast for Crows|George R. R. Martin",
    "The Ballad of Songbirds and Snakes|Suzanne Collins",
    "Soumission|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Under the Dome|Stephen King",
    "A Dance with Dragons|George R. R. Martin",
    "Colorless Tsukuru Tazaki and His Years of Pilgrimage|Haruki Murakami",
    "The God Delusion|Richard Dawkins",
    "Doctor Sleep|Stephen King",
    "Mr. Mercedes|Stephen King",
    "The Grand Design|Stephen Hawking",
    "The Mysterious Flame of Queen Loana|Umberto Eco",
    "The Road|Cormac McCarthy",
    "Metro 2033|Dmitry Glukhovsky",
    "The Bad Beginning|Daniel Handler"
  ],
  es: [
    "Eragon|Christopher Paolini",
    "Eldest|Christopher Paolini",
    "Divergente|Veronica Roth",
    "Insurgente|Veronica Roth",
    "Brisingr|Christopher Paolini",
    "The devil wears Prada|Lauren Weisberger",
    "American Psycho|Bret Easton Ellis",
    "Legado|Christopher Paolini",
    "Medio sol amarillo|Chimamanda Ngozi Adichie",
    "Metro 2034|Dmitri Glujovski",
    "Un hombre llamado Ove|Fredrik Backman",
    "El hogar de Miss Peregrine para niños peculiares|Ransom Riggs",
    "Luna nueva|Stephenie Meyer",
    "Eclipse|Stephenie Meyer",
    "Bajo la misma estrella|John Green",
    "Ángeles y demonios|Dan Brown",
    "Romper el círculo (novela)|Colleen Hoover",
    "The Forty Rules of Love|Elif Shafak",
    "Homo Deus: Breve historia del mañana|Yuval Noah Harari",
    "Criadas y señoras|Kathryn Stockett",
    "El ladrón del rayo|Rick Riordan",
    "El capital en el siglo XXI|Thomas Piketty",
    "La chica del tren|Paula Hawkins",
    "La batalla del laberinto|Rick Riordan",
    "Por qué fracasan los países|Daron Acemoğlu",
    "El héroe perdido|Rick Riordan",
    "Sol de medianoche|Stephenie Meyer",
    "Y las montañas hablaron|Jaled Hosseini",
    "Proyecto Hail Mary|Andy Weir",
    "El jilguero|Donna Tartt",
    "Nunca me abandones|Kazuo Ishiguro",
    "La Tierra es plana|Thomas Friedman",
    "Origen|Dan Brown",
    "El cazador de sueños|Stephen King",
    "1001 Albums You Must Hear Before You Die|Robert Dimery",
    "El museo de la inocencia|Orhan Pamuk",
    "Festín de cuervos|George R. R. Martin",
    "Balada de pájaros cantores y serpientes|Suzanne Collins",
    "Sumisión|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Duma Key|Stephen King",
    "La cúpula|Stephen King",
    "Danza de dragones|George R. R. Martin",
    "Los años de peregrinación del chico sin color|Haruki Murakami",
    "El viento por la cerradura|Stephen King",
    "Doctor Sleep|Stephen King",
    "Mr. Mercedes|Stephen King",
    "Killing Commendatore|Haruki Murakami",
    "La chica salvaje|Delia Owens",
    "Fuego y sangre|George R. R. Martin"
  ],
  pt: [
    "Eragon|Christopher Paolini",
    "Eldest|Christopher Paolini",
    "Divergente|Veronica Roth",
    "Insurgente|Veronica Roth",
    "Brisingr|Christopher Paolini",
    "The Devil Wears Prada|Lauren Weisberger",
    "American Psycho|Bret Easton Ellis",
    "Inheritance|Christopher Paolini",
    "Half of a Yellow Sun|Chimamanda Ngozi Adichie",
    "Metro 2034|Dmitriy Glukhovskiy",
    "A Man Called Ove|Fredrik Backman",
    "Miss Peregrine's Home for Peculiar Children|Ransom Riggs",
    "Lua Nova|Stephenie Meyer",
    "Eclipse|Stephenie Meyer",
    "The Fault in Our Stars|John Green",
    "Angels & Demons|Dan Brown",
    "It Ends with Us|Colleen Hoover",
    "The Forty Rules of Love|Elif Şafak",
    "Homo Deus – Uma Breve História do Amanhã|Yuval Noah Harari",
    "The Help|Kathryn Stockett",
    "The Lightning Thief|Rick Riordan",
    "O Capital no século XXI|Thomas Piketty",
    "The Girl on the Train|Paula Hawkins",
    "The Battle of the Labyrinth|Rick Riordan",
    "Por que as nações fracassam|Daron Acemoglu",
    "The Lost Hero|Rick Riordan",
    "Midnight Sun|Stephenie Meyer",
    "And the Mountains Echoed|Khaled Hosseini",
    "Project Hail Mary|Andy Weir",
    "O Pintassilgo|Donna Tartt",
    "Män som hatar kvinnor|Stieg Larsson",
    "O Mundo É Plano: uma Breve História do Século XXI|Thomas Friedman",
    "Origem|Dan Brown",
    "Dreamcatcher|Stephen King",
    "1001 Albums You Must Hear Before You Die|Robert Dimery",
    "The Museum of Innocence|Orhan Pamuk",
    "A Feast for Crows|George R. R. Martin",
    "The Ballad of Songbirds and Snakes|Suzanne Collins",
    "Submissão|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Duma Key|Stephen King",
    "Under the Dome|Stephen King",
    "A Dance with Dragons|George R. R. Martin",
    "A Peregrinação do Rapaz Sem Cor|Haruki Murakami",
    "A Torre Negra: O Vento pela Fechadura|Stephen King",
    "Doutor Sono|Stephen King",
    "Mr. Mercedes|Stephen King",
    "Killing Commendatore|Haruki Murakami",
    "Where the Crawdads Sing|Delia Owens",
    "Fire & Blood|George R. R. Martin"
  ],
  fr: [
    "Eragon|Christopher Paolini",
    "L'Aîné|Christopher Paolini",
    "Divergent|Veronica Roth",
    "Divergente 2|Veronica Roth",
    "Brisingr|Christopher Paolini",
    "Le Diable s'habille en Prada|Lauren Weisberger",
    "American Psycho|Bret Easton Ellis",
    "L'Héritage|Christopher Paolini",
    "L'Autre Moitié du soleil|Chimamanda Ngozi Adichie",
    "Métro 2034|Dmitri Gloukhovski",
    "Vieux, râleur et suicidaire : La vie selon Ove|Fredrik Backman",
    "Miss Peregrine et les enfants particuliers|Ransom Riggs",
    "Tentation|Stephenie Meyer",
    "Hésitation|Stephenie Meyer",
    "Nos Étoiles contraires|John Green",
    "Anges et Démons|Dan Brown",
    "Jamais plus|Colleen Hoover",
    "The Forty Rules of Love|Elif Shafak",
    "Homo Deus : Une brève histoire du futur|Yuval Noah Harari",
    "La Couleur des sentiments|Kathryn Stockett",
    "Le Voleur de foudre|Rick Riordan",
    "Le Capital au XXIe siècle|Thomas Piketty",
    "La Fille du train|Paula Hawkins",
    "La Bataille du labyrinthe|Rick Riordan",
    "Why Nations Fail|Daron Acemoğlu",
    "Le Héros perdu|Rick Riordan",
    "Midnight Sun|Stephenie Meyer",
    "Ainsi résonne l'écho infini des montagnes|Khaled Hosseini",
    "Projet Dernière Chance|Andy Weir",
    "Le Chardonneret|Donna Tartt",
    "Les Hommes qui n'aimaient pas les femmes|Stieg Larsson",
    "Ce cher Dexter|Jeff Lindsay",
    "Origine|Dan Brown",
    "Dreamcatcher|Stephen King",
    "1001 Albums You Must Hear Before You Die|Robert Dimery",
    "Le Musée de l'innocence|Orhan Pamuk",
    "A Feast for Crows|George R. R. Martin",
    "La Ballade du serpent et de l'Oiseau chanteur|Suzanne Collins",
    "Soumission|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Duma Key|Stephen King",
    "Dôme|Stephen King",
    "A Dance with Dragons|George R. R. Martin",
    "L'Incolore Tsukuru Tazaki et ses années de pèlerinage|Haruki Murakami",
    "La Clé des vents|Stephen King",
    "Docteur Sleep|Stephen King",
    "Mr. Mercedes|Stephen King",
    "Le Meurtre du Commandeur|Haruki Murakami",
    "Là où chantent les écrevisses|Delia Owens",
    "Feu et Sang|George R. R. Martin"
  ],
  de: [
    "Eragon - Das Vermächtnis der Drachenreiter|Christopher Paolini",
    "Eragon - Der Auftrag des Ältesten|Christopher Paolini",
    "Die Bestimmung|Veronica Roth",
    "Die Bestimmung - Tödliche Wahrheit|Veronica Roth",
    "Eragon - Die Weisheit des Feuers|Christopher Paolini",
    "Der Teufel trägt Prada|Lauren Weisberger",
    "American Psycho|Bret Easton Ellis",
    "Eragon - Das Erbe der Macht|Christopher Paolini",
    "Half of a Yellow Sun|Chimamanda Ngozi Adichie",
    "Metro 2034|Dmitri Alexejewitsch Gluchowski",
    "Ein Mann namens Ove|Fredrik Backman",
    "Die Insel der besonderen Kinder|Ransom Riggs",
    "Bis(s) zur Mittagsstunde|Stephenie Meyer",
    "Bis(s) zum Abendrot|Stephenie Meyer",
    "Das Schicksal ist ein mieser Verräter|John Green",
    "Phantastische Tierwesen & wo sie zu finden sind|Joanne K. Rowling",
    "Nur noch ein einziges Mal|Colleen Hoover",
    "Die vierzig Geheimnisse der Liebe|Elif Shafak",
    "Homo Deus - Eine Geschichte von Morgen|Yuval Noah Harari",
    "Gute Geister|Kathryn Stockett",
    "Percy Jackson – Diebe im Olymp|Rick Riordan",
    "Das Kapital im 21. Jahrhundert|Thomas Piketty",
    "Girl on the Train|Paula Hawkins",
    "Percy Jackson – Die Schlacht um das Labyrinth|Rick Riordan",
    "Warum Nationen scheitern|Daron Acemoğlu",
    "Helden des Olymp – Der verschwundene Halbgott|Rick Riordan",
    "Midnight Sun|Stephenie Meyer",
    "Der Ruf des Kuckucks|Joanne K. Rowling",
    "Der Astronaut|Andy Weir",
    "Der Distelfink|Donna Tartt",
    "Alles, was wir geben mussten|Kazuo Ishiguro",
    "Darkly Dreaming Dexter|Jeff Lindsay",
    "Origin|Dan Brown",
    "Duddits|Stephen King",
    "1001 Albums You Must Hear Before You Die|Robert Dimery",
    "Das Museum der Unschuld|Orhan Pamuk",
    "Krähenfest|George R. R. Martin",
    "Die Tribute von Panem X – Das Lied von Vogel und Schlange|Suzanne Collins",
    "Unterwerfung|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Wahn|Stephen King",
    "Die Arena|Stephen King",
    "Ein Tanz mit Drachen|George R. R. Martin",
    "Die Pilgerjahre des farblosen Herrn Tazaki|Haruki Murakami",
    "Wind|Stephen King",
    "Doctor Sleep|Stephen King",
    "Mr. Mercedes|Stephen King",
    "Die Ermordung des Commendatore|Haruki Murakami",
    "Der Gesang der Flusskrebse|Delia Owens",
    "Fire & Blood|George R. R. Martin"
  ],
  it: [
    "Eragon|Christopher Paolini",
    "Eldest|Christopher Paolini",
    "Divergent|Veronica Roth",
    "Insurgent|Veronica Roth",
    "Brisingr|Christopher Paolini",
    "Il diavolo veste Prada|Lauren Weisberger",
    "American Psycho|Bret Easton Ellis",
    "Inheritance|Christopher Paolini",
    "Metà di un sole giallo|Chimamanda Ngozi Adichie",
    "Metro 2034|Dmitrij Gluchovskij",
    "A Man Called Ove|Fredrik Backman",
    "La casa dei bambini speciali di Miss Peregrine|Ransom Riggs",
    "New Moon|Stephenie Meyer",
    "Eclipse|Stephenie Meyer",
    "Colpa delle stelle|John Green",
    "Angeli e demoni|Dan Brown",
    "It Ends With Us - Siamo noi a dire basta|Colleen Hoover",
    "Le quaranta porte|Elif Şafak",
    "La storia di domani|Yuval Noah Harari",
    "L'aiuto|Kathryn Stockett",
    "Percy Jackson e gli dei dell'Olimpo: il ladro di fulmini (romanzo)|Rick Riordan",
    "Il capitale nel XXI secolo|Thomas Piketty",
    "La ragazza del treno|Paula Hawkins",
    "Percy Jackson e gli dei dell'Olimpo: la battaglia del labirinto|Rick Riordan",
    "Perché le nazioni falliscono|Daron Acemoğlu",
    "Eroi dell'Olimpo: l'eroe perduto|Rick Riordan",
    "Midnight Sun|Stephenie Meyer",
    "E l'eco rispose|Khaled Hosseini",
    "Project Hail Mary|Andy Weir",
    "Il cardellino|Donna Tartt",
    "Uomini che odiano le donne|Stieg Larsson",
    "Il mondo è piatto|Thomas Lauren Friedman",
    "Origin|Dan Brown",
    "L'acchiappasogni|Stephen King",
    "1001 Albums You Must Hear Before You Die|Robert Dimery",
    "Il museo dell'innocenza|Orhan Pamuk",
    "A Feast for Crows|George R. R. Martin",
    "Hunger Games: Ballata dell'usignolo e del serpente|Suzanne Collins",
    "Sottomissione|Michel Houellebecq",
    "1Q84|Haruki Murakami",
    "Duma Key|Stephen King",
    "The Dome|Stephen King",
    "A Dance with Dragons|George R. R. Martin",
    "L'incolore Tazaki Tsukuru e i suoi anni di pellegrinaggio|Haruki Murakami",
    "La leggenda del vento|Stephen King",
    "Doctor Sleep|Stephen King",
    "Mr. Mercedes|Stephen King",
    "L'assassinio del commendatore|Haruki Murakami",
    "La ragazza della palude|Delia Owens",
    "Fuoco e sangue|George R. R. Martin"
  ]
};
